image: node:10.15.0
pipelines:
  default:
    - step:
        script:
          - npm install
          - docker build -t deepakdocker25/nodejsapp:v1 .
          - docker images
        services:
          - docker
