pipelines:
  default:
      - step:
          runs-on:
            - self.hosted
            - linux.shell
          script:
            - pwd
            - ls -la
            - whoami
            - cat Dockerfile
            - sudo docker ps
            - sudo docker build -t deepakdocker25/nodeapp:v1 .
          