pipelines:
  default:
      - step:
          name: Build
          runs-on:
            - self.hosted
            - linux.shell
          script:
            - sudo docker build -t deepakdocker25/nodeapp:v1 .
      
      - step:
          name: Deploy
          runs-on:
            - self.hosted
            - linux.shell
          script:
            - sudo docker login -u $uname -p $password

          