pipelines:
  default:
      - step:
          runs-on:
            - self.hosted
            - linux.shell
          script:
            - pwd
            - ls -la
            - sudo docker build -t deepakdocker25/nodeapp:v1 .
          